set -x
node scripts/jest --config packages/core/application/core-application-browser-internal/jest.integration.config.js
node scripts/jest --config packages/kbn-cli-dev-mode/jest.integration.config.js
node scripts/jest --config packages/kbn-docs-utils/jest.integration.config.js
node scripts/jest --config packages/kbn-es/jest.integration.config.js
node scripts/jest --config packages/kbn-import-resolver/jest.integration.config.js
node scripts/jest --config packages/kbn-plugin-generator/jest.integration.config.js
node scripts/jest --config packages/kbn-plugin-helpers/jest.integration.config.js
node scripts/jest --config packages/kbn-test/jest.integration.config.js
node scripts/jest --config src/cli/jest.integration.config.js
node scripts/jest --config src/core/public/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/capabilities/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/config/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/core_app/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/elasticsearch/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/execution_context/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/http/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/http_resources/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/logging/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/metrics/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/node/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/saved_objects/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/saved_objects/migrations/group1/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/saved_objects/migrations/group3/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/status/jest.integration.config.js
node scripts/jest --config src/core/server/integration_tests/ui_settings/jest.integration.config.js
node scripts/jest --config src/dev/jest.integration.config.js
node scripts/jest --config src/plugins/content_management/jest.integration.config.js
node scripts/jest --config src/plugins/files/jest.integration.config.js
node scripts/jest --config src/plugins/kibana_usage_collection/jest.integration.config.js
node scripts/jest --config src/plugins/usage_collection/jest.integration.config.js
node scripts/jest --config x-pack/plugins/actions/jest.integration.config.js
node scripts/jest --config x-pack/plugins/fleet/jest.integration.config.js
node scripts/jest --config x-pack/plugins/global_search/jest.integration.config.js
node scripts/jest --config x-pack/plugins/index_lifecycle_management/jest.integration.config.js
node scripts/jest --config x-pack/plugins/reporting/jest.integration.config.js
node scripts/jest --config x-pack/plugins/screenshotting/jest.integration.config.js
node scripts/jest --config x-pack/plugins/security_solution/jest.integration.config.js
node scripts/jest --config x-pack/plugins/task_manager/jest.integration.config.js
