diff --git a/Makefile b/Makefile
index 0d0865188..c1b1a97cb 100755
--- a/Makefile
+++ b/Makefile
@@ -176,7 +176,7 @@ integration: out/minikube
 
 .PHONY: integration-none-driver
 integration-none-driver: e2e-linux-$(GOARCH) out/minikube-linux-$(GOARCH)
-	sudo -E out/e2e-linux-$(GOARCH) -testdata-dir "test/integration/testdata" -minikube-start-args="--vm-driver=none" -test.v -test.timeout=60m -binary=out/minikube-linux-amd64 $(TEST_ARGS)
+	sudo -E out/e2e-linux-$(GOARCH) -testdata-dir "test/integration/testdata" -minikube-start-args="--vm-driver=none" -test.v -test.timeout=60m -binary=out/minikube-linux-s390x $(TEST_ARGS)
 
 .PHONY: integration-versioned
 integration-versioned: out/minikube
