diff --git a/Makefile b/Makefile
index 4d250bac5..8af22a2ce 100755
--- a/Makefile
+++ b/Makefile
@@ -330,8 +330,8 @@ gocyclo:
 
 out/linters/golangci-lint-$(GOLINT_VERSION):
 	mkdir -p out/linters
-	curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b out/linters $(GOLINT_VERSION)
-	mv out/linters/golangci-lint out/linters/golangci-lint-$(GOLINT_VERSION)
+	go get github.com/golangci/golangci-lint/cmd/golangci-lint@$(GOLINT_VERSION)
+	cp $(GOPATH)/bin/golangci-lint out/linters/golangci-lint-$(GOLINT_VERSION)
 
 # this one is meant for local use
 .PHONY: lint
