/*
* © Copyright IBM Corporation 2026
* LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
*/

pipeline {
    agent {
        docker {
            image 'osuosl/ubuntu-s390x:22.04'
            label 's390x-docker2'
        }
    }
    
    triggers {
        // Trigger build immediately when GitHub pushes a webhook notification
        githubPush()
    }
    
    stages {
        stage('Checkout Envoy') {
			options {
				timeout(time: 5, unit: 'MINUTES')
			}
            steps {
                script {
                    dir('envoy') {
						// Shallow clone of repository
						checkout([
							$class: 'GitSCM',
							branches: [[name: '*/main']],
							extensions: [
								[$class: 'CloneOption', depth: 1, noTags: false, shallow: true]
							],
							userRemoteConfigs: [[url: 'https://github.com/envoyproxy/envoy.git']]
						])
                    }    
                }
            }
        }
        
                
        stage('Build Envoy') {
            steps {
                script {
					try {
	                    sh '''
							wget -O build_envoy.sh https://raw.githubusercontent.com/linux-on-ibm-z/scripts/refs/heads/master/CI/Envoy/build_envoy.sh
							ls -l
							bash build_envoy.sh -y
						'''
					} catch (Exception e) {
                		currentBuild.result = 'FAILURE'
                		echo "Envoy build failed: ${e.message}"
                		throw e
				    }
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
