set -x
node scripts/jest --config examples/content_management_examples/jest.config.js
node scripts/jest --config packages/analytics/client/jest.config.js
node scripts/jest --config packages/analytics/shippers/elastic_v3/browser/jest.config.js
node scripts/jest --config packages/analytics/shippers/elastic_v3/common/jest.config.js
node scripts/jest --config packages/analytics/shippers/elastic_v3/server/jest.config.js
node scripts/jest --config packages/analytics/shippers/fullstory/jest.config.js
node scripts/jest --config packages/analytics/shippers/gainsight/jest.config.js
node scripts/jest --config packages/content-management/content_editor/jest.config.js
node scripts/jest --config packages/content-management/table_list/jest.config.js
node scripts/jest --config packages/core/analytics/core-analytics-browser-internal/jest.config.js
node scripts/jest --config packages/core/analytics/core-analytics-browser-mocks/jest.config.js
node scripts/jest --config packages/core/analytics/core-analytics-browser/jest.config.js
node scripts/jest --config packages/core/analytics/core-analytics-server-internal/jest.config.js
node scripts/jest --config packages/core/analytics/core-analytics-server-mocks/jest.config.js
node scripts/jest --config packages/core/analytics/core-analytics-server/jest.config.js
node scripts/jest --config packages/core/application/core-application-browser-internal/jest.config.js
node scripts/jest --config packages/core/application/core-application-browser-mocks/jest.config.js
node scripts/jest --config packages/core/application/core-application-browser/jest.config.js
node scripts/jest --config packages/core/application/core-application-common/jest.config.js
node scripts/jest --config packages/core/apps/core-apps-browser-internal/jest.config.js
node scripts/jest --config packages/core/apps/core-apps-browser-mocks/jest.config.js
node scripts/jest --config packages/core/apps/core-apps-server-internal/jest.config.js
node scripts/jest --config packages/core/base/core-base-browser-internal/jest.config.js
node scripts/jest --config packages/core/base/core-base-browser-mocks/jest.config.js
node scripts/jest --config packages/core/base/core-base-common-internal/jest.config.js
node scripts/jest --config packages/core/base/core-base-common/jest.config.js
node scripts/jest --config packages/core/base/core-base-server-internal/jest.config.js
node scripts/jest --config packages/core/base/core-base-server-mocks/jest.config.js
node scripts/jest --config packages/core/capabilities/core-capabilities-browser-internal/jest.config.js
node scripts/jest --config packages/core/capabilities/core-capabilities-browser-mocks/jest.config.js
node scripts/jest --config packages/core/capabilities/core-capabilities-common/jest.config.js
node scripts/jest --config packages/core/capabilities/core-capabilities-server-internal/jest.config.js
node scripts/jest --config packages/core/capabilities/core-capabilities-server-mocks/jest.config.js
node scripts/jest --config packages/core/capabilities/core-capabilities-server/jest.config.js
node scripts/jest --config packages/core/chrome/core-chrome-browser-internal/jest.config.js
node scripts/jest --config packages/core/chrome/core-chrome-browser-mocks/jest.config.js
node scripts/jest --config packages/core/chrome/core-chrome-browser/jest.config.js
node scripts/jest --config packages/core/config/core-config-server-internal/jest.config.js
node scripts/jest --config packages/core/custom-branding/core-custom-branding-browser-internal/jest.config.js
node scripts/jest --config packages/core/custom-branding/core-custom-branding-browser-mocks/jest.config.js
node scripts/jest --config packages/core/custom-branding/core-custom-branding-server-internal/jest.config.js
node scripts/jest --config packages/core/custom-branding/core-custom-branding-server-mocks/jest.config.js
node scripts/jest --config packages/core/deprecations/core-deprecations-browser-internal/jest.config.js
node scripts/jest --config packages/core/deprecations/core-deprecations-browser-mocks/jest.config.js
node scripts/jest --config packages/core/deprecations/core-deprecations-browser/jest.config.js
node scripts/jest --config packages/core/deprecations/core-deprecations-common/jest.config.js
node scripts/jest --config packages/core/deprecations/core-deprecations-server-internal/jest.config.js
node scripts/jest --config packages/core/deprecations/core-deprecations-server-mocks/jest.config.js
node scripts/jest --config packages/core/deprecations/core-deprecations-server/jest.config.js
node scripts/jest --config packages/core/doc-links/core-doc-links-browser-internal/jest.config.js
node scripts/jest --config packages/core/doc-links/core-doc-links-browser-mocks/jest.config.js
node scripts/jest --config packages/core/doc-links/core-doc-links-browser/jest.config.js
node scripts/jest --config packages/core/doc-links/core-doc-links-server-internal/jest.config.js
node scripts/jest --config packages/core/doc-links/core-doc-links-server-mocks/jest.config.js
node scripts/jest --config packages/core/doc-links/core-doc-links-server/jest.config.js
node scripts/jest --config packages/core/elasticsearch/core-elasticsearch-client-server-internal/jest.config.js
node scripts/jest --config packages/core/elasticsearch/core-elasticsearch-client-server-mocks/jest.config.js
node scripts/jest --config packages/core/elasticsearch/core-elasticsearch-server-internal/jest.config.js
node scripts/jest --config packages/core/elasticsearch/core-elasticsearch-server-mocks/jest.config.js
node scripts/jest --config packages/core/elasticsearch/core-elasticsearch-server/jest.config.js
node scripts/jest --config packages/core/environment/core-environment-server-internal/jest.config.js
node scripts/jest --config packages/core/environment/core-environment-server-mocks/jest.config.js
node scripts/jest --config packages/core/execution-context/core-execution-context-browser-internal/jest.config.js
node scripts/jest --config packages/core/execution-context/core-execution-context-browser-mocks/jest.config.js
node scripts/jest --config packages/core/execution-context/core-execution-context-browser/jest.config.js
node scripts/jest --config packages/core/execution-context/core-execution-context-common/jest.config.js
node scripts/jest --config packages/core/execution-context/core-execution-context-server-internal/jest.config.js
node scripts/jest --config packages/core/execution-context/core-execution-context-server-mocks/jest.config.js
node scripts/jest --config packages/core/execution-context/core-execution-context-server/jest.config.js
node scripts/jest --config packages/core/fatal-errors/core-fatal-errors-browser-internal/jest.config.js
node scripts/jest --config packages/core/fatal-errors/core-fatal-errors-browser-mocks/jest.config.js
node scripts/jest --config packages/core/fatal-errors/core-fatal-errors-browser/jest.config.js
node scripts/jest --config packages/core/http/core-http-browser-internal/jest.config.js
node scripts/jest --config packages/core/http/core-http-browser-mocks/jest.config.js
node scripts/jest --config packages/core/http/core-http-browser/jest.config.js
node scripts/jest --config packages/core/http/core-http-common/jest.config.js
node scripts/jest --config packages/core/http/core-http-context-server-internal/jest.config.js
node scripts/jest --config packages/core/http/core-http-context-server-mocks/jest.config.js
node scripts/jest --config packages/core/http/core-http-request-handler-context-server-internal/jest.config.js
node scripts/jest --config packages/core/http/core-http-request-handler-context-server/jest.config.js
node scripts/jest --config packages/core/http/core-http-resources-server-internal/jest.config.js
node scripts/jest --config packages/core/http/core-http-resources-server-mocks/jest.config.js
node scripts/jest --config packages/core/http/core-http-resources-server/jest.config.js
node scripts/jest --config packages/core/http/core-http-router-server-internal/jest.config.js
node scripts/jest --config packages/core/http/core-http-router-server-mocks/jest.config.js
node scripts/jest --config packages/core/http/core-http-server-internal/jest.config.js
node scripts/jest --config packages/core/http/core-http-server-mocks/jest.config.js
node scripts/jest --config packages/core/http/core-http-server/jest.config.js
node scripts/jest --config packages/core/i18n/core-i18n-browser-internal/jest.config.js
node scripts/jest --config packages/core/i18n/core-i18n-browser-mocks/jest.config.js
node scripts/jest --config packages/core/i18n/core-i18n-browser/jest.config.js
node scripts/jest --config packages/core/i18n/core-i18n-server-internal/jest.config.js
node scripts/jest --config packages/core/i18n/core-i18n-server-mocks/jest.config.js
node scripts/jest --config packages/core/i18n/core-i18n-server/jest.config.js
node scripts/jest --config packages/core/injected-metadata/core-injected-metadata-browser-internal/jest.config.js
node scripts/jest --config packages/core/injected-metadata/core-injected-metadata-browser-mocks/jest.config.js
node scripts/jest --config packages/core/injected-metadata/core-injected-metadata-common-internal/jest.config.js
node scripts/jest --config packages/core/integrations/core-integrations-browser-internal/jest.config.js
node scripts/jest --config packages/core/integrations/core-integrations-browser-mocks/jest.config.js
node scripts/jest --config packages/core/lifecycle/core-lifecycle-browser-internal/jest.config.js
node scripts/jest --config packages/core/lifecycle/core-lifecycle-browser-mocks/jest.config.js
node scripts/jest --config packages/core/lifecycle/core-lifecycle-browser/jest.config.js
node scripts/jest --config packages/core/lifecycle/core-lifecycle-server-internal/jest.config.js
node scripts/jest --config packages/core/lifecycle/core-lifecycle-server-mocks/jest.config.js
node scripts/jest --config packages/core/lifecycle/core-lifecycle-server/jest.config.js
node scripts/jest --config packages/core/logging/core-logging-browser-internal/jest.config.js
node scripts/jest --config packages/core/logging/core-logging-browser-mocks/jest.config.js
node scripts/jest --config packages/core/logging/core-logging-common-internal/jest.config.js
node scripts/jest --config packages/core/logging/core-logging-server-internal/jest.config.js
node scripts/jest --config packages/core/logging/core-logging-server-mocks/jest.config.js
node scripts/jest --config packages/core/logging/core-logging-server/jest.config.js
node scripts/jest --config packages/core/metrics/core-metrics-collectors-server-internal/jest.config.js
node scripts/jest --config packages/core/metrics/core-metrics-collectors-server-mocks/jest.config.js
node scripts/jest --config packages/core/metrics/core-metrics-server-internal/jest.config.js
node scripts/jest --config packages/core/metrics/core-metrics-server-mocks/jest.config.js
node scripts/jest --config packages/core/metrics/core-metrics-server/jest.config.js
node scripts/jest --config packages/core/mount-utils/core-mount-utils-browser-internal/jest.config.js
node scripts/jest --config packages/core/mount-utils/core-mount-utils-browser/jest.config.js
node scripts/jest --config packages/core/node/core-node-server-internal/jest.config.js
node scripts/jest --config packages/core/node/core-node-server-mocks/jest.config.js
node scripts/jest --config packages/core/node/core-node-server/jest.config.js
node scripts/jest --config packages/core/notifications/core-notifications-browser-internal/jest.config.js
node scripts/jest --config packages/core/notifications/core-notifications-browser-mocks/jest.config.js
node scripts/jest --config packages/core/notifications/core-notifications-browser/jest.config.js
node scripts/jest --config packages/core/overlays/core-overlays-browser-internal/jest.config.js
node scripts/jest --config packages/core/overlays/core-overlays-browser-mocks/jest.config.js
node scripts/jest --config packages/core/overlays/core-overlays-browser/jest.config.js
node scripts/jest --config packages/core/plugins/core-plugins-base-server-internal/jest.config.js
node scripts/jest --config packages/core/plugins/core-plugins-browser-internal/jest.config.js
node scripts/jest --config packages/core/plugins/core-plugins-browser-mocks/jest.config.js
node scripts/jest --config packages/core/plugins/core-plugins-browser/jest.config.js
node scripts/jest --config packages/core/plugins/core-plugins-server-internal/jest.config.js
node scripts/jest --config packages/core/plugins/core-plugins-server-mocks/jest.config.js
node scripts/jest --config packages/core/plugins/core-plugins-server/jest.config.js
node scripts/jest --config packages/core/preboot/core-preboot-server-internal/jest.config.js
node scripts/jest --config packages/core/preboot/core-preboot-server-mocks/jest.config.js
node scripts/jest --config packages/core/preboot/core-preboot-server/jest.config.js
node scripts/jest --config packages/core/rendering/core-rendering-browser-internal/jest.config.js
node scripts/jest --config packages/core/rendering/core-rendering-browser-mocks/jest.config.js
node scripts/jest --config packages/core/rendering/core-rendering-server-internal/jest.config.js
node scripts/jest --config packages/core/rendering/core-rendering-server-mocks/jest.config.js
node scripts/jest --config packages/core/root/core-root-browser-internal/jest.config.js
node scripts/jest --config packages/core/root/core-root-server-internal/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-api-browser/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-api-server-internal/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-api-server-mocks/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-api-server/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-base-server-internal/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-base-server-mocks/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-browser-internal/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-browser-mocks/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-browser/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-common/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-import-export-server-internal/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-import-export-server-mocks/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-migration-server-internal/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-migration-server-mocks/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-server-internal/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-server-mocks/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-server/jest.config.js
node scripts/jest --config packages/core/saved-objects/core-saved-objects-utils-server/jest.config.js
node scripts/jest --config packages/core/status/core-status-common-internal/jest.config.js
node scripts/jest --config packages/core/status/core-status-common/jest.config.js
node scripts/jest --config packages/core/status/core-status-server-internal/jest.config.js
node scripts/jest --config packages/core/status/core-status-server-mocks/jest.config.js
node scripts/jest --config packages/core/status/core-status-server/jest.config.js
node scripts/jest --config packages/core/test-helpers/core-test-helpers-deprecations-getters/jest.config.js
node scripts/jest --config packages/core/test-helpers/core-test-helpers-http-setup-browser/jest.config.js
node scripts/jest --config packages/core/test-helpers/core-test-helpers-kbn-server/jest.config.js
node scripts/jest --config packages/core/test-helpers/core-test-helpers-so-type-serializer/jest.config.js
node scripts/jest --config packages/core/test-helpers/core-test-helpers-test-utils/jest.config.js
node scripts/jest --config packages/core/theme/core-theme-browser-internal/jest.config.js
node scripts/jest --config packages/core/theme/core-theme-browser-mocks/jest.config.js
node scripts/jest --config packages/core/theme/core-theme-browser/jest.config.js
node scripts/jest --config packages/core/ui-settings/core-ui-settings-browser-internal/jest.config.js
node scripts/jest --config packages/core/ui-settings/core-ui-settings-browser-mocks/jest.config.js
node scripts/jest --config packages/core/ui-settings/core-ui-settings-browser/jest.config.js
node scripts/jest --config packages/core/ui-settings/core-ui-settings-common/jest.config.js
node scripts/jest --config packages/core/ui-settings/core-ui-settings-server-internal/jest.config.js
node scripts/jest --config packages/core/ui-settings/core-ui-settings-server-mocks/jest.config.js
node scripts/jest --config packages/core/ui-settings/core-ui-settings-server/jest.config.js
node scripts/jest --config packages/core/usage-data/core-usage-data-base-server-internal/jest.config.js
node scripts/jest --config packages/core/usage-data/core-usage-data-server-internal/jest.config.js
node scripts/jest --config packages/core/usage-data/core-usage-data-server-mocks/jest.config.js
node scripts/jest --config packages/core/usage-data/core-usage-data-server/jest.config.js
node scripts/jest --config packages/core/user-settings/core-user-settings-server-internal/jest.config.js
node scripts/jest --config packages/core/user-settings/core-user-settings-server-mocks/jest.config.js
node scripts/jest --config packages/home/sample_data_card/jest.config.js
node scripts/jest --config packages/home/sample_data_tab/jest.config.js
node scripts/jest --config packages/home/sample_data_types/jest.config.js
node scripts/jest --config packages/kbn-alerts-ui-shared/jest.config.js
node scripts/jest --config packages/kbn-alerts/jest.config.js
node scripts/jest --config packages/kbn-ambient-common-types/jest.config.js
node scripts/jest --config packages/kbn-ambient-ftr-types/jest.config.js
node scripts/jest --config packages/kbn-apm-config-loader/jest.config.js
node scripts/jest --config packages/kbn-apm-synthtrace-client/jest.config.js
node scripts/jest --config packages/kbn-apm-synthtrace/jest.config.js
node scripts/jest --config packages/kbn-babel-transform/jest.config.js
node scripts/jest --config packages/kbn-cases-components/jest.config.js
node scripts/jest --config packages/kbn-cell-actions/jest.config.js
node scripts/jest --config packages/kbn-chart-icons/jest.config.js
node scripts/jest --config packages/kbn-ci-stats-performance-metrics/jest.config.js
node scripts/jest --config packages/kbn-ci-stats-shipper-cli/jest.config.js
node scripts/jest --config packages/kbn-cli-dev-mode/jest.config.js
node scripts/jest --config packages/kbn-coloring/jest.config.js
node scripts/jest --config packages/kbn-config-mocks/jest.config.js
node scripts/jest --config packages/kbn-config-schema/jest.config.js
node scripts/jest --config packages/kbn-config/jest.config.js
node scripts/jest --config packages/kbn-content-management-utils/jest.config.js
node scripts/jest --config packages/kbn-crypto-browser/jest.config.js
node scripts/jest --config packages/kbn-crypto/jest.config.js
node scripts/jest --config packages/kbn-cypress-config/jest.config.js
node scripts/jest --config packages/kbn-datemath/jest.config.js
node scripts/jest --config packages/kbn-dev-cli-errors/jest.config.js
node scripts/jest --config packages/kbn-dev-cli-runner/jest.config.js
node scripts/jest --config packages/kbn-dev-proc-runner/jest.config.js
node scripts/jest --config packages/kbn-dev-utils/jest.config.js
node scripts/jest --config packages/kbn-doc-links/jest.config.js
node scripts/jest --config packages/kbn-docs-utils/jest.config.js
node scripts/jest --config packages/kbn-dom-drag-drop/jest.config.js
node scripts/jest --config packages/kbn-ebt-tools/jest.config.js
node scripts/jest --config packages/kbn-ecs/jest.config.js
node scripts/jest --config packages/kbn-es-archiver/jest.config.js
node scripts/jest --config packages/kbn-es-errors/jest.config.js
node scripts/jest --config packages/kbn-es-query/jest.config.js
node scripts/jest --config packages/kbn-es-types/jest.config.js
node scripts/jest --config packages/kbn-es/jest.config.js
node scripts/jest --config packages/kbn-eslint-plugin-disable/jest.config.js
node scripts/jest --config packages/kbn-eslint-plugin-eslint/jest.config.js
node scripts/jest --config packages/kbn-eslint-plugin-imports/jest.config.js
node scripts/jest --config packages/kbn-eslint-plugin-telemetry/jest.config.js
node scripts/jest --config packages/kbn-expandable-flyout/jest.config.js
node scripts/jest --config packages/kbn-failed-test-reporter-cli/jest.config.js
node scripts/jest --config packages/kbn-field-types/jest.config.js
node scripts/jest --config packages/kbn-find-used-node-modules/jest.config.js
node scripts/jest --config packages/kbn-ftr-common-functional-services/jest.config.js
node scripts/jest --config packages/kbn-ftr-screenshot-filename/jest.config.js
node scripts/jest --config packages/kbn-generate-csv/jest.config.js
node scripts/jest --config packages/kbn-get-repo-files/jest.config.js
node scripts/jest --config packages/kbn-guided-onboarding/jest.config.js
node scripts/jest --config packages/kbn-handlebars/jest.config.js
node scripts/jest --config packages/kbn-hapi-mocks/jest.config.js
node scripts/jest --config packages/kbn-health-gateway-server/jest.config.js
node scripts/jest --config packages/kbn-i18n-react/jest.config.js
node scripts/jest --config packages/kbn-i18n/jest.config.js
node scripts/jest --config packages/kbn-import-locator/jest.config.js
node scripts/jest --config packages/kbn-interpreter/jest.config.js
node scripts/jest --config packages/kbn-io-ts-utils/jest.config.js
node scripts/jest --config packages/kbn-journeys/jest.config.js
node scripts/jest --config packages/kbn-json-ast/jest.config.js
node scripts/jest --config packages/kbn-kibana-manifest-schema/jest.config.js
node scripts/jest --config packages/kbn-language-documentation-popover/jest.config.js
node scripts/jest --config packages/kbn-lint-packages-cli/jest.config.js
node scripts/jest --config packages/kbn-lint-ts-projects-cli/jest.config.js
node scripts/jest --config packages/kbn-logging/jest.config.js
node scripts/jest --config packages/kbn-managed-vscode-config-cli/jest.config.js
node scripts/jest --config packages/kbn-managed-vscode-config/jest.config.js
node scripts/jest --config packages/kbn-monaco/jest.config.js
node scripts/jest --config packages/kbn-object-versioning/jest.config.js
node scripts/jest --config packages/kbn-optimizer-webpack-helpers/jest.config.js
node scripts/jest --config packages/kbn-optimizer/jest.config.js
node scripts/jest --config packages/kbn-osquery-io-ts-types/jest.config.js
node scripts/jest --config packages/kbn-peggy-loader/jest.config.js
node scripts/jest --config packages/kbn-peggy/jest.config.js
node scripts/jest --config packages/kbn-performance-testing-dataset-extractor/jest.config.js
node scripts/jest --config packages/kbn-picomatcher/jest.config.js
node scripts/jest --config packages/kbn-plugin-generator/jest.config.js
node scripts/jest --config packages/kbn-react-field/jest.config.js
node scripts/jest --config packages/kbn-repo-file-maps/jest.config.js
node scripts/jest --config packages/kbn-repo-info/jest.config.js
node scripts/jest --config packages/kbn-repo-linter/jest.config.js
node scripts/jest --config packages/kbn-repo-packages/jest.config.js
node scripts/jest --config packages/kbn-repo-path/jest.config.js
node scripts/jest --config packages/kbn-repo-source-classifier-cli/jest.config.js
node scripts/jest --config packages/kbn-repo-source-classifier/jest.config.js
node scripts/jest --config packages/kbn-reporting/common/jest.config.js
node scripts/jest --config packages/kbn-rison/jest.config.js
node scripts/jest --config packages/kbn-saved-objects-settings/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-autocomplete/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-ecs/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-es-utils/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-exception-list-components/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-grouping/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-hook-utils/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-io-ts-alerting-types/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-io-ts-list-types/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-io-ts-types/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-io-ts-utils/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-list-api/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-list-hooks/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-list-utils/jest.config.js
node scripts/jest --config packages/kbn-securitysolution-utils/jest.config.js
node scripts/jest --config packages/kbn-server-http-tools/jest.config.js
node scripts/jest --config packages/kbn-server-route-repository/jest.config.js
node scripts/jest --config packages/kbn-set-map/jest.config.js
node scripts/jest --config packages/kbn-shared-svg/jest.config.js
node scripts/jest --config packages/kbn-shared-ux-utility/jest.config.js
node scripts/jest --config packages/kbn-slo-schema/jest.config.js
node scripts/jest --config packages/kbn-some-dev-log/jest.config.js
node scripts/jest --config packages/kbn-spec-to-console/jest.config.js
node scripts/jest --config packages/kbn-std/jest.config.js
node scripts/jest --config packages/kbn-telemetry-tools/jest.config.js
node scripts/jest --config packages/kbn-test-jest-helpers/jest.config.js
node scripts/jest --config packages/kbn-test-subj-selector/jest.config.js
node scripts/jest --config packages/kbn-test/jest.config.js
node scripts/jest --config packages/kbn-tinymath/jest.config.js
node scripts/jest --config packages/kbn-tooling-log/jest.config.js
node scripts/jest --config packages/kbn-ts-projects/jest.config.js
node scripts/jest --config packages/kbn-ts-type-check-cli/jest.config.js
node scripts/jest --config packages/kbn-typed-react-router-config/jest.config.js
node scripts/jest --config packages/kbn-ui-actions-browser/jest.config.js
node scripts/jest --config packages/kbn-url-state/jest.config.js
node scripts/jest --config packages/kbn-user-profile-components/jest.config.js
node scripts/jest --config packages/kbn-utils/jest.config.js
node scripts/jest --config packages/kbn-validate-next-docs-cli/jest.config.js
node scripts/jest --config packages/kbn-web-worker-stub/jest.config.js
node scripts/jest --config packages/kbn-whereis-pkg-cli/jest.config.js
node scripts/jest --config packages/kbn-yarn-lock-validator/jest.config.js
node scripts/jest --config packages/shared-ux/avatar/solution/jest.config.js
node scripts/jest --config packages/shared-ux/avatar/user_profile/impl/jest.config.js
node scripts/jest --config packages/shared-ux/button/exit_full_screen/impl/jest.config.js
node scripts/jest --config packages/shared-ux/button_toolbar/jest.config.js
node scripts/jest --config packages/shared-ux/card/no_data/impl/jest.config.js
node scripts/jest --config packages/shared-ux/code_editor/impl/jest.config.js
node scripts/jest --config packages/shared-ux/code_editor/mocks/jest.config.js
node scripts/jest --config packages/shared-ux/code_editor/types/jest.config.js
node scripts/jest --config packages/shared-ux/file/file_picker/impl/jest.config.js
node scripts/jest --config packages/shared-ux/file/file_upload/impl/jest.config.js
node scripts/jest --config packages/shared-ux/file/util/jest.config.js
node scripts/jest --config packages/shared-ux/link/redirect_app/impl/jest.config.js
node scripts/jest --config packages/shared-ux/markdown/impl/jest.config.js
node scripts/jest --config packages/shared-ux/page/analytics_no_data/impl/jest.config.js
node scripts/jest --config packages/shared-ux/page/kibana_no_data/impl/jest.config.js
node scripts/jest --config packages/shared-ux/page/kibana_template/impl/jest.config.js
node scripts/jest --config packages/shared-ux/page/no_data/impl/jest.config.js
node scripts/jest --config packages/shared-ux/page/no_data_config/impl/jest.config.js
node scripts/jest --config packages/shared-ux/page/solution_nav/jest.config.js
node scripts/jest --config packages/shared-ux/prompt/no_data_views/impl/jest.config.js
node scripts/jest --config packages/shared-ux/prompt/not_found/jest.config.js
node scripts/jest --config packages/shared-ux/router/impl/jest.config.js
node scripts/jest --config packages/shared-ux/router/mocks/jest.config.js
node scripts/jest --config src/cli/jest.config.js
node scripts/jest --config src/cli_encryption_keys/jest.config.js
node scripts/jest --config src/cli_keystore/jest.config.js
node scripts/jest --config src/cli_plugin/jest.config.js
node scripts/jest --config src/cli_setup/jest.config.js
node scripts/jest --config src/core/public/jest.config.js
node scripts/jest --config src/core/server/jest.config.js
node scripts/jest --config src/dev/jest.config.js
node scripts/jest --config src/plugins/advanced_settings/jest.config.js
node scripts/jest --config src/plugins/bfetch/jest.config.js
node scripts/jest --config src/plugins/chart_expressions/common/jest.config.js
node scripts/jest --config src/plugins/chart_expressions/expression_gauge/jest.config.js
node scripts/jest --config src/plugins/chart_expressions/expression_heatmap/jest.config.js
node scripts/jest --config src/plugins/chart_expressions/expression_legacy_metric/jest.config.js
node scripts/jest --config src/plugins/chart_expressions/expression_metric/jest.config.js
node scripts/jest --config src/plugins/chart_expressions/expression_partition_vis/jest.config.js
node scripts/jest --config src/plugins/chart_expressions/expression_tagcloud/jest.config.js
node scripts/jest --config src/plugins/chart_expressions/expression_xy/jest.config.js
node scripts/jest --config src/plugins/charts/jest.config.js
node scripts/jest --config src/plugins/console/jest.config.js
node scripts/jest --config src/plugins/content_management/jest.config.js
node scripts/jest --config src/plugins/controls/jest.config.js
node scripts/jest --config src/plugins/custom_integrations/jest.config.js
node scripts/jest --config src/plugins/dashboard/jest.config.js
node scripts/jest --config src/plugins/data/jest.config.js
node scripts/jest --config src/plugins/data_view_editor/jest.config.js
node scripts/jest --config src/plugins/data_view_field_editor/jest.config.js
node scripts/jest --config src/plugins/data_view_management/jest.config.js
node scripts/jest --config src/plugins/data_views/jest.config.js
node scripts/jest --config src/plugins/discover/jest.config.js
node scripts/jest --config src/plugins/embeddable/jest.config.js
node scripts/jest --config src/plugins/es_ui_shared/jest.config.js
node scripts/jest --config src/plugins/event_annotation/jest.config.js
node scripts/jest --config src/plugins/expression_image/jest.config.js
node scripts/jest --config src/plugins/expression_metric/jest.config.js
node scripts/jest --config src/plugins/expression_repeat_image/jest.config.js
node scripts/jest --config src/plugins/expression_reveal_image/jest.config.js
node scripts/jest --config src/plugins/expression_shape/jest.config.js
node scripts/jest --config src/plugins/expressions/jest.config.js
node scripts/jest --config src/plugins/field_formats/jest.config.js
node scripts/jest --config src/plugins/files/jest.config.js
node scripts/jest --config src/plugins/ftr_apis/jest.config.js
node scripts/jest --config src/plugins/guided_onboarding/jest.config.js
node scripts/jest --config src/plugins/home/jest.config.js
node scripts/jest --config src/plugins/image_embeddable/jest.config.js
node scripts/jest --config src/plugins/input_control_vis/jest.config.js
node scripts/jest --config src/plugins/inspector/jest.config.js
node scripts/jest --config src/plugins/interactive_setup/jest.config.js
node scripts/jest --config src/plugins/kibana_overview/jest.config.js
node scripts/jest --config src/plugins/kibana_react/jest.config.js
node scripts/jest --config src/plugins/kibana_usage_collection/jest.config.js
node scripts/jest --config src/plugins/kibana_utils/jest.config.js
node scripts/jest --config src/plugins/management/jest.config.js
node scripts/jest --config src/plugins/maps_ems/jest.config.js
node scripts/jest --config src/plugins/navigation/jest.config.js
node scripts/jest --config src/plugins/newsfeed/jest.config.js
node scripts/jest --config src/plugins/presentation_util/jest.config.js
node scripts/jest --config src/plugins/saved_objects/jest.config.js
node scripts/jest --config src/plugins/saved_objects_finder/jest.config.js
node scripts/jest --config src/plugins/saved_objects_management/jest.config.js
node scripts/jest --config src/plugins/saved_objects_tagging_oss/jest.config.js
node scripts/jest --config src/plugins/saved_search/jest.config.js
node scripts/jest --config src/plugins/screenshot_mode/jest.config.js
node scripts/jest --config src/plugins/share/jest.config.js
node scripts/jest --config src/plugins/telemetry/jest.config.js
node scripts/jest --config src/plugins/telemetry_collection_manager/jest.config.js
node scripts/jest --config src/plugins/telemetry_management_section/jest.config.js
node scripts/jest --config src/plugins/ui_actions/jest.config.js
node scripts/jest --config src/plugins/ui_actions_enhanced/jest.config.js
node scripts/jest --config src/plugins/unified_field_list/jest.config.js
node scripts/jest --config src/plugins/unified_histogram/jest.config.js
node scripts/jest --config src/plugins/unified_search/jest.config.js
node scripts/jest --config src/plugins/url_forwarding/jest.config.js
node scripts/jest --config src/plugins/usage_collection/jest.config.js
node scripts/jest --config src/plugins/vis_default_editor/jest.config.js
node scripts/jest --config src/plugins/vis_type_markdown/jest.config.js
node scripts/jest --config src/plugins/vis_types/gauge/jest.config.js
node scripts/jest --config src/plugins/vis_types/heatmap/jest.config.js
node scripts/jest --config src/plugins/vis_types/metric/jest.config.js
node scripts/jest --config src/plugins/vis_types/pie/jest.config.js
node scripts/jest --config src/plugins/vis_types/table/jest.config.js
node scripts/jest --config src/plugins/vis_types/tagcloud/jest.config.js
node scripts/jest --config src/plugins/vis_types/timelion/jest.config.js
node scripts/jest --config src/plugins/vis_types/timeseries/jest.config.js
node scripts/jest --config src/plugins/vis_types/vega/jest.config.js
node scripts/jest --config src/plugins/vis_types/vislib/jest.config.js
node scripts/jest --config src/plugins/vis_types/xy/jest.config.js
node scripts/jest --config src/plugins/visualizations/jest.config.js
node scripts/jest --config src/setup_node_env/jest.config.js
node scripts/jest --config test/analytics/plugins/analytics_ftr_helpers/jest.config.js
node scripts/jest --config test/api_integration/jest.config.js
node scripts/jest --config test/functional/jest.config.js
node scripts/jest --config x-pack/examples/alerting_example/jest.config.js
node scripts/jest --config x-pack/packages/kbn-alerting-state-types/jest.config.js
node scripts/jest --config x-pack/packages/kbn-elastic-assistant/jest.config.js
node scripts/jest --config x-pack/packages/ml/agg_utils/jest.config.js
node scripts/jest --config x-pack/packages/ml/aiops_components/jest.config.js
node scripts/jest --config x-pack/packages/ml/aiops_utils/jest.config.js
node scripts/jest --config x-pack/packages/ml/date_picker/jest.config.js
node scripts/jest --config x-pack/packages/ml/error_utils/jest.config.js
node scripts/jest --config x-pack/packages/ml/is_defined/jest.config.js
node scripts/jest --config x-pack/packages/ml/is_populated_object/jest.config.js
node scripts/jest --config x-pack/packages/ml/kibana_theme/jest.config.js
node scripts/jest --config x-pack/packages/ml/local_storage/jest.config.js
node scripts/jest --config x-pack/packages/ml/nested_property/jest.config.js
node scripts/jest --config x-pack/packages/ml/number_utils/jest.config.js
node scripts/jest --config x-pack/packages/ml/query_utils/jest.config.js
node scripts/jest --config x-pack/packages/ml/random_sampler_utils/jest.config.js
node scripts/jest --config x-pack/packages/ml/route_utils/jest.config.js
node scripts/jest --config x-pack/packages/ml/string_hash/jest.config.js
node scripts/jest --config x-pack/packages/ml/trained_models_utils/jest.config.js
node scripts/jest --config x-pack/packages/ml/url_state/jest.config.js
node scripts/jest --config x-pack/packages/observability/alert_details/jest.config.js
node scripts/jest --config x-pack/packages/security-solution/data_table/jest.config.js
node scripts/jest --config x-pack/packages/security-solution/ecs_data_quality_dashboard/jest.config.js
node scripts/jest --config x-pack/packages/security-solution/side_nav/jest.config.js
node scripts/jest --config x-pack/performance/jest.config.js
node scripts/jest --config x-pack/plugins/actions/jest.config.js
node scripts/jest --config x-pack/plugins/aiops/jest.config.js
node scripts/jest --config x-pack/plugins/alerting/jest.config.js
node scripts/jest --config x-pack/plugins/apm/jest.config.js
node scripts/jest --config x-pack/plugins/banners/jest.config.js
node scripts/jest --config x-pack/plugins/canvas/jest.config.js
node scripts/jest --config x-pack/plugins/cases/jest.config.js
node scripts/jest --config x-pack/plugins/cloud/jest.config.js
node scripts/jest --config x-pack/plugins/cloud_defend/jest.config.js
node scripts/jest --config x-pack/plugins/cloud_integrations/cloud_chat/jest.config.js
node scripts/jest --config x-pack/plugins/cloud_integrations/cloud_data_migration/jest.config.js
node scripts/jest --config x-pack/plugins/cloud_integrations/cloud_experiments/jest.config.js
node scripts/jest --config x-pack/plugins/cloud_integrations/cloud_full_story/jest.config.js
node scripts/jest --config x-pack/plugins/cloud_integrations/cloud_gain_sight/jest.config.js
node scripts/jest --config x-pack/plugins/cloud_integrations/cloud_links/jest.config.js
node scripts/jest --config x-pack/plugins/cloud_security_posture/jest.config.js
node scripts/jest --config x-pack/plugins/cross_cluster_replication/jest.config.js
node scripts/jest --config x-pack/plugins/dashboard_enhanced/jest.config.js
node scripts/jest --config x-pack/plugins/data_visualizer/jest.config.js
node scripts/jest --config x-pack/plugins/discover_enhanced/jest.config.js
node scripts/jest --config x-pack/plugins/drilldowns/jest.config.js
node scripts/jest --config x-pack/plugins/ecs_data_quality_dashboard/jest.config.js
node scripts/jest --config x-pack/plugins/embeddable_enhanced/jest.config.js
node scripts/jest --config x-pack/plugins/encrypted_saved_objects/jest.config.js
node scripts/jest --config x-pack/plugins/enterprise_search/common/jest.config.js
node scripts/jest --config x-pack/plugins/enterprise_search/public/jest.config.js
node scripts/jest --config x-pack/plugins/enterprise_search/server/jest.config.js
node scripts/jest --config x-pack/plugins/event_log/jest.config.js
node scripts/jest --config x-pack/plugins/exploratory_view/jest.config.js
node scripts/jest --config x-pack/plugins/features/jest.config.js
node scripts/jest --config x-pack/plugins/file_upload/jest.config.js
node scripts/jest --config x-pack/plugins/fleet/jest.config.js
node scripts/jest --config x-pack/plugins/global_search/jest.config.js
node scripts/jest --config x-pack/plugins/global_search_bar/jest.config.js
node scripts/jest --config x-pack/plugins/global_search_providers/jest.config.js
node scripts/jest --config x-pack/plugins/graph/jest.config.js
node scripts/jest --config x-pack/plugins/grokdebugger/jest.config.js
node scripts/jest --config x-pack/plugins/index_lifecycle_management/jest.config.js
node scripts/jest --config x-pack/plugins/index_management/jest.config.js
node scripts/jest --config x-pack/plugins/infra/jest.config.js
node scripts/jest --config x-pack/plugins/ingest_pipelines/jest.config.js
node scripts/jest --config x-pack/plugins/kubernetes_security/jest.config.js
node scripts/jest --config x-pack/plugins/lens/jest.config.js
node scripts/jest --config x-pack/plugins/license_api_guard/jest.config.js
node scripts/jest --config x-pack/plugins/license_management/jest.config.js
node scripts/jest --config x-pack/plugins/licensing/jest.config.js
node scripts/jest --config x-pack/plugins/lists/jest.config.js
node scripts/jest --config x-pack/plugins/logstash/jest.config.js
node scripts/jest --config x-pack/plugins/maps/jest.config.js
node scripts/jest --config x-pack/plugins/ml/jest.config.js
node scripts/jest --config x-pack/plugins/monitoring/jest.config.js
node scripts/jest --config x-pack/plugins/monitoring_collection/jest.config.js
node scripts/jest --config x-pack/plugins/notifications/jest.config.js
node scripts/jest --config x-pack/plugins/observability/jest.config.js
node scripts/jest --config x-pack/plugins/observability_onboarding/jest.config.js
node scripts/jest --config x-pack/plugins/observability_shared/jest.config.js
node scripts/jest --config x-pack/plugins/osquery/jest.config.js
node scripts/jest --config x-pack/plugins/painless_lab/jest.config.js
node scripts/jest --config x-pack/plugins/profiling/jest.config.js
node scripts/jest --config x-pack/plugins/remote_clusters/jest.config.js
node scripts/jest --config x-pack/plugins/reporting/jest.config.js
node scripts/jest --config x-pack/plugins/rollup/jest.config.js
node scripts/jest --config x-pack/plugins/rule_registry/jest.config.js
node scripts/jest --config x-pack/plugins/runtime_fields/jest.config.js
node scripts/jest --config x-pack/plugins/saved_objects_tagging/jest.config.js
node scripts/jest --config x-pack/plugins/screenshotting/jest.config.js
node scripts/jest --config x-pack/plugins/searchprofiler/jest.config.js
node scripts/jest --config x-pack/plugins/security/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/common/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/actions/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/app/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/assistant/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/cases/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/common/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/dashboards/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/detection_engine/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/detections/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/exceptions/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/explore/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/flyout/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/landing_pages/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/management/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/overview/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/resolver/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/public/timelines/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/server/client/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/server/endpoint/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/server/fleet_integration/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/server/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/server/lib/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/server/lists_integration/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/server/search_strategy/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/server/usage/jest.config.js
node scripts/jest --config x-pack/plugins/security_solution/server/utils/jest.config.js
node scripts/jest --config x-pack/plugins/session_view/jest.config.js
node scripts/jest --config x-pack/plugins/snapshot_restore/jest.config.js
node scripts/jest --config x-pack/plugins/spaces/jest.config.js
node scripts/jest --config x-pack/plugins/stack_alerts/jest.config.js
node scripts/jest --config x-pack/plugins/stack_connectors/jest.config.js
node scripts/jest --config x-pack/plugins/synthetics/jest.config.js
node scripts/jest --config x-pack/plugins/task_manager/jest.config.js
node scripts/jest --config x-pack/plugins/telemetry_collection_xpack/jest.config.js
node scripts/jest --config x-pack/plugins/threat_intelligence/jest.config.js
node scripts/jest --config x-pack/plugins/timelines/jest.config.js
node scripts/jest --config x-pack/plugins/transform/jest.config.js
node scripts/jest --config x-pack/plugins/triggers_actions_ui/jest.config.js
node scripts/jest --config x-pack/plugins/upgrade_assistant/jest.config.js
node scripts/jest --config x-pack/plugins/ux/jest.config.js
node scripts/jest --config x-pack/test/alerting_api_integration/packages/helpers/jest.config.js
node scripts/jest --config x-pack/test/security_api_integration/packages/helpers/jest.config.js