/*
* © Copyright IBM Corporation 2026
* LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
*/

pipeline {
    agent {
        docker {
            image 'osuosl/ubuntu-s390x:22.04'
            label 's390x-docker1'
        }
    }
    
     triggers {
        // Trigger build immediately when GitHub pushes a webhook notification
        githubPush()
    }
    
    stages {
        stage('Checkout Tensorflow') {
			options {
				timeout(time: 5, unit: 'MINUTES')
			}
            steps {
                script {
                    dir('tensorflow') {
						// Shallow clone of repository
						checkout([
							$class: 'GitSCM',
							branches: [[name: '*/master']],
							extensions: [
								[$class: 'CloneOption', depth: 1, noTags: false, shallow: true]
							],
							userRemoteConfigs: [[url: 'https://github.com/tensorflow/tensorflow.git']]
						])
                    }    
                }
            }
        }
        
        stage('Build Tensorflow') {
            steps {
                script {
					try {
						sh '''
							pwd
							ls
							wget -O build_tensorflow.sh https://raw.githubusercontent.com/linux-on-ibm-z/scripts/refs/heads/master/CI/Tensorflow/build_tensorflow.sh
							bash build_tensorflow.sh -y
						'''
					} catch (Exception e) {
                		currentBuild.result = 'FAILURE'
                		echo "Tensorflow build failed: ${e.message}"
                		throw e
				    }
                }
            }
        }
		stage('Archive Artifacts') {
            steps {
                script {
                    // Verify .whl files exist before archiving
                    sh 'ls -lh tensorflow_whl/*.whl'
                    archiveArtifacts artifacts: 'tensorflow_whl/*.whl', fingerprint: true
                }
            }
        }
    }
    
    post {
        always {
            cleanWs()
        }
    }
}
