/*
* © Copyright IBM Corporation 2026
* LICENSE: Apache License, Version 2.0 (http://www.apache.org/licenses/LICENSE-2.0)
*/

pipeline {
    agent {
        docker {
            image 'osuosl/ubuntu-s390x:22.04'
            label 's390x-docker1'
        }
    }
    
    options {
        // Shallow clone for the main repository
        skipDefaultCheckout()
    }
    
    stages {
        stage('Checkout Tensorflow') {
			options {
				timeout(time: 5, unit: 'MINUTES')
			}
            steps {
                script {
                    dir('tensorflow') {
						// Shallow clone of repository
						checkout([
							$class: 'GitSCM',
							branches: [[name: '*/master']],
							extensions: [
								[$class: 'CloneOption', depth: 1, noTags: false, shallow: true]
							],
							userRemoteConfigs: [[url: 'https://github.com/tensorflow/tensorflow.git']]
						])
                    }    
                }
            }
        }
        
        stage('Checkout Build files') {
			options {
				timeout(time: 5, unit: 'MINUTES')
			}
            steps {
                script {
                    // Checkout CI/Tensorflow folder from scripts repository
                    dir('scripts-repo') {
                        checkout([
                            $class: 'GitSCM',
                            branches: [[name: '*/master']],
                            extensions: [
                                [$class: 'SparseCheckoutPaths', 
                                 sparseCheckoutPaths: [[path: 'CI/Tensorflow/*']]]
                            ],
                            userRemoteConfigs: [[url: 'https://github.com/linux-on-ibm-z/scripts.git']]
                        ])
                    }
                }
            }
        }
        
        stage('Build Tensorflow') {
            steps {
                script {
					try {
						sh '''
							pwd
							cp scripts-repo/CI/Tensorflow/build_tensorflow.sh .
							cp -r scripts-repo/CI/Tensorflow/patch .
							bash build_tensorflow.sh -y
						'''
					} catch (Exception e) {
                		currentBuild.result = 'FAILURE'
                		echo "Tensorflow build failed: ${e.message}"
                		throw e
				    }
                }
            }
        }
    }
    
    post {
		success {
            archiveArtifacts artifacts: '/home/alfred/jenkins/workspace/TensorFlow_IBMZ_CI_test/tensorflow_whl/*.whl', fingerprint: true
        }
        always {
            cleanWs()
        }
    }
}
